# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8eedc53caac3f0bb4396097b6a0bd44134b0cf939f78796b1fc9092154c9a88aea7043d4e5f06a1fc9f2fbae90f1de359198af6f3d38f7d9c696d1f291989534

test:
  secret_key_base: 8f95ee84a649dbcc34dee49a51a3d0a9d4bc0baee19892ad892c067d078480ebaf56c0976b67e427d5d83edc7fc6f2db7144f51134e62b9bb0d4544b1c9d90e5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
